# Generated by Django 5.0.3 on 2024-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_post')),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(default=0)),
                ('cap', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
